SELECT pff_DEFTEAM,
PLAYS = SUM(CASE WHEN pff_RUNPASS <> '' THEN 1 ELSE 0 END), --pff_MOFOCSHOWN, pff_MOFOCPLAYED -- pff_PASSRESULT, pff_MOFOCPLAYED, pff_MOFOCSHOWN, pff_EXPECTEDPOINTS, pff_EXPECTEDPOINTSADDED
SHOWN_NOT_PLAYED = SUM(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN THEN 1 ELSE 0 END),
SHOWN_NOT_PLAYED_RATE = AVG(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN THEN CAST(1 AS FLOAT) ELSE 0 END),
SHOWN_NOT_PLAYED_EP = AVG(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN THEN pff_EXPECTEDPOINTS ELSE 0 END),
SHOWN_NOT_PLAYED_EPA = AVG(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN THEN pff_EXPECTEDPOINTSADDED ELSE 0 END),
SHOWN_NOT_PLAYED_PBU = SUM(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN AND pff_PASSRESULT = 'INCOMPLETE' AND pff_PASSBREAKUP <> '' THEN 1 ELSE 0 END),
SHOWN_NOT_PLAYED_PBU_RATE = AVG(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN AND pff_PASSRESULT = 'INCOMPLETE' AND pff_PASSBREAKUP <> '' THEN CAST(1 AS FLOAT) ELSE 0 END),
SHOWN_NOT_PLAYED_INTS = SUM(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN AND pff_PASSRESULT = 'INTERCEPTION' THEN 1 ELSE 0 END),
SHOWN_NOT_PLAYED_INT_RATE = AVG(CASE WHEN pff_MOFOCPLAYED <> pff_MOFOCSHOWN AND pff_PASSRESULT = 'INTERCEPTION' THEN CAST(1 AS FLOAT) ELSE 0 END),
SHOWN_PLAYED = SUM(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN THEN 1 ELSE 0 END),
SHOWN_PLAYED_RATE = AVG(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN THEN CAST(1 AS FLOAT) ELSE 0 END),
SHOWN_PLAYED_EP = AVG(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN THEN pff_EXPECTEDPOINTS ELSE 0 END),
SHOWN_PLAYED_EPA = AVG(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN THEN pff_EXPECTEDPOINTSADDED ELSE 0 END),
SHOWN_PLAYED_PBU = SUM(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN AND pff_PASSRESULT = 'INCOMPLETE' AND pff_PASSBREAKUP <> '' THEN 1 ELSE 0 END),
SHOWN_PLAYED_PBU_RATE = AVG(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN AND pff_PASSRESULT = 'INCOMPLETE' AND pff_PASSBREAKUP <> '' THEN CAST(1 AS FLOAT) ELSE 0 END),
SHOWN_PLAYED_INTS = SUM(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN AND pff_PASSRESULT = 'INTERCEPTION' THEN 1 ELSE 0 END),
SHOWN_PLAYED_INT_RATE = AVG(CASE WHEN pff_MOFOCPLAYED = pff_MOFOCSHOWN AND pff_PASSRESULT = 'INTERCEPTION' THEN CAST(1 AS FLOAT) ELSE 0 END)
FROM PFFPlays
WHERE pff_GAMESEASON = 2022 AND pff_MOFOCPLAYED <> '' AND pff_MOFOCSHOWN <> ''
group by pff_DEFTEAM
ORDER BY pff_DEFTEAM