---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(nflfastR)
library(nfl4th)
library(ranger)
library(vip)
library(shapper)
library(ggimage)
library(data.table)
```


```{r}
pbp_2pt<- load_pbp(2011:2021)
```


```{r}
pbp_just_2pt<- pbp_2pt %>%
  filter(two_point_attempt == 1) %>%
  mutate(success = ifelse(two_point_conv_result == "success", 1, 0))
```


```{r}
team_2pt<- pbp_2pt %>%
  group_by(posteam) %>%
  summarize(plays_2pt = n(),
            success_rate= mean(success)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))
```


```{r}
# team_2pt %>%
#   ggplot(aes(x = plays_2pt, y = success_rate)) +
#   geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.05) +
#   theme_minimal() +
#   labs(x = "Amount of 2pt. Conversion Attempts",
#        y = "2pt. Conversion Success Rate",
#        title = "Each NFL Team's 2 Point Conversion Breakdown Since 2015") +
#   theme(axis.text = element_text(size = 12),
#         plot.title = element_text(size = 20, face = "bold"))

```

#################### MAKE 2PT CONVERSION RATE #######################

```{r}
off_epa_5 <- pbp_just_2pt %>%
  filter(two_point_attempt == 1) %>%
  mutate(success = ifelse(two_point_conv_result == "success", 1, 0))

pbp_xp<- pbp_2pt %>%
  filter(extra_point_attempt == 1)

```


```{r}
off_epa_5<- pbp_2pt %>%
  filter(yardline_100 <= 5, !is.na(epa)) %>%
  group_by(posteam, season) %>%
  summarize(plays_in_5 = n(),
            epa_in_5 = mean(epa))

```

```{r}
def_epa_5<- pbp_2pt %>%
  filter(yardline_100 <= 5, !is.na(epa)) %>%
  group_by(defteam, season) %>%
  summarize(plays_in_5 = n(),
            epa_in_5 = mean(epa))
```

```{r}
pbp_just_2pt <- pbp_just_2pt %>%
  left_join(off_epa_5, by = c("posteam", "season")) %>%
  left_join(def_epa_5, by = c("defteam", "season")) 
  
```

```{r}
pbp_just_2pt<- pbp_just_2pt %>%
  rename(off_epa_in_5 = epa_in_5.x, def_epa_in_5 = epa_in_5.y)

```


```{r}
log_2pt <- glm(success ~ off_epa_in_5 + def_epa_in_5 + game_seconds_remaining + score_differential,
                  data = pbp_just_2pt, family = "binomial")

summary(log_2pt)

```


```{r}
pred_2pt<- ifelse(log_2pt$fitted.values > 0.5, "1", "0")

pbp_just_2pt<- pbp_just_2pt %>%
  mutate(pred = log_2pt$fitted.values)

```


```{r}
pbp_2pt_select<- pbp_just_2pt %>%
  select(off_epa_in_5, def_epa_in_5, game_seconds_remaining, pred, two_point_conv_result) %>%
  mutate(rec = ifelse(pred > 0.5, 1, 0),
         pred_correct = ifelse(rec == two_point_conv_result, 1, 0))

```



```{r}
pbp_2pt_select %>% 
  group_by(rec, two_point_conv_result) %>% 
  tally(sort = T) %>%
  ggplot(aes(x = as.factor(rec), y = as.factor(two_point_conv_result))) +
  geom_tile(aes(fill = n)) +
  geom_text(aes(label = n), size = 5) +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(x = "2 Point Predicted Conversion",
       y = "2 Point Down Actual Conversion",
       title = "Confusion Matrix for Expected 2 Point Conversions (52.6% Accuracy)",
       subtitle = "1 = Conversion, 0 = Failure")

```

```{r}
model_2pt_data<- pbp_just_2pt %>%
  select(label = success, off_epa_in_5, def_epa_in_5, game_seconds_remaining, score_differential)


```


```{r}
nrounds <- 100
params <-
  list(
    booster = "gbtree",
    objective = "binary:logistic",
    eval_metric = c("logloss"),
    eta = 0.025,
    gamma = 5,
    subsample = 0.8,
    colsample_bytree = 0.8,
    max_depth = 4,
    min_child_weight = 6,
    base_score = mean(model_2pt_data$label)
  )

```


```{r}
full_train_2pt <- xgboost::xgb.DMatrix(model.matrix(~ . + 0, data = model_2pt_data %>% select(-label)),
                                       label = model_2pt_data$label)
model_2pt <- xgboost::xgboost(params = params, data = full_train_2pt, nrounds = nrounds, verbose = 2)

vip(model_2pt, num_features = 5)

```


```{r}
pbp_xp <- pbp_2pt %>%
  filter(extra_point_attempt == 1) %>%
  mutate(xp_made = ifelse(extra_point_result == "good", 1, 0))

team_xp_rate <- pbp_xp %>%
  group_by(posteam, season) %>%
  summarize(xps = n(),
            xp_make_rate = mean(xp_made))

pbp_xp <- pbp_xp %>%
  left_join(team_xp_rate, by = c("posteam", "season"))

log_xp <- glm(xp_made ~ season + xp_make_rate + game_seconds_remaining, 
              data = pbp_xp, family = "binomial")
```


```{r}
pbp_just_xp <- pbp_xp %>%
  mutate(xp_made = ifelse(extra_point_result == "good", 1, 0))

```


```{r}
xp_per_game<- pbp_just_xp %>%
  select(game_id, kicker_player_id, kicker_player_name, game_seconds_remaining, xp_made)

```


```{r}
xp_missed<- xp_per_game %>%
  filter(xp_made == 0) %>%
  select(game_id, kicker_player_id, kicker_player_name, time_missed = game_seconds_remaining) %>%
  group_by(kicker_player_id, kicker_player_name) %>%
  mutate(count = row_number()) %>%
  ungroup() %>%
  distinct() %>%
  filter(count == 1)


xp_per_game<- xp_per_game %>%
  left_join(xp_missed, by = c("game_id", "kicker_player_id", "kicker_player_name"))

```



```{r}
xp_per_game <- xp_per_game %>%
  mutate(prev_missed = ifelse(game_seconds_remaining < time_missed, 1, 0),
         prev_missed = ifelse(is.na(prev_missed), 0, prev_missed)) %>%
  select(game_id, kicker_player_id, game_seconds_remaining, prev_missed)

pbp_xp <- pbp_xp %>%
  mutate(xp_made = ifelse(extra_point_result == "good", 1, 0)) %>%
  left_join(xp_per_game, by = c("game_id", "kicker_player_id", "game_seconds_remaining"))

```



```{r}
xp_logit<- glm(xp_made ~ xp_make_rate + game_seconds_remaining, data = pbp_just_xp, family = "binomial")

summary(xp_logit)

```


```{r}
pbp_xp_select <- pbp_xp %>%
  select(posteam, season, game_seconds_remaining, extra_point_attempt, xp_made) %>%
  mutate(pred_prob = as.numeric(xp_logit$fitted.values)) %>%
  mutate(pred_xp = as.numeric(ifelse(pred_prob > 0.75, 1, 0)),
         xp_correct = as.numeric(ifelse(pred_xp == xp_made, 1, 0)))



```


```{r}
pbp_xp_select %>% 
  group_by(pred_xp, xp_correct) %>% 
  tally(sort = T) %>%
  ggplot(aes(x = as.factor(pred_xp), y = as.factor(xp_correct))) +
  geom_tile(aes(fill = n)) +
  geom_text(aes(label = n), size = 5) +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(x = "Extra Point Prediction",
       y = "Extra Point Actual",
       title = "Confusion Matrix for Extra Point Predictions (95.8% Accuracy)",
       subtitle = "1 = Conversion, 0 = Failure")



```

################################ Build The Model ################################ 


```{r}
success_2pt<- pbp_just_2pt %>%
  filter(!is.na(wpa)) %>%
  filter(success == 1) %>%
  mutate(wpa = ifelse(wpa < 0, -wpa, wpa))

```

#Add Gameflow Here on Game and Drive

```{r}
success_2pt_rf<- ranger(wpa ~ game_seconds_remaining + score_differential + off_epa_in_5 + def_epa_in_5, data = success_2pt, num.trees = 100, importance = "impurity")

vip(success_2pt_rf)

success_2pt_rf$r.squared 
```

```{r}
fail_2pt<- pbp_just_2pt %>%
  filter(!is.na(wpa)) %>%
  filter(success != 1) %>%
  mutate(wpa = ifelse(wpa > 0, -wpa, wpa))


```


#Add Gameflow Here on Game and Drive

```{r}
fail_2pt_rf<- ranger(wpa ~ game_seconds_remaining + score_differential + off_epa_in_5 + def_epa_in_5, data = fail_2pt, num.trees = 100, importance = "impurity")

vip(fail_2pt_rf)

fail_2pt_rf$r.squared 
```

```{r}
made_xp<- pbp_just_xp %>%
  filter(xp_made == 1) %>%
  filter(!is.na(wpa)) 
  

```


```{r}
made_xp_rf <- ranger(wpa ~ game_seconds_remaining + score_differential, data = pbp_just_xp, num.trees = 100, importance = "impurity")

vip(made_xp_rf)

made_xp_rf$r.squared
```

```{r}
miss_xp<- pbp_just_xp %>%
  filter(xp_made != 1) %>%
  filter(!is.na(wpa))
  

```


```{r}
miss_xp_rf <- ranger(wpa ~ game_seconds_remaining + score_differential, data = pbp_just_xp, num.trees = 100, importance = "impurity")

vip(miss_xp_rf)

miss_xp_rf$r.squared
```

```{r}
model_xp_data<- pbp_just_xp %>%
  select(label = xp_made, xp_make_rate, score_differential, game_seconds_remaining)


```


```{r}
nrounds <- 100
params <-
  list(
    booster = "gbtree",
    objective = "binary:logistic",
    eval_metric = c("logloss"),
    eta = 0.025,
    gamma = 5,
    subsample = 0.8,
    colsample_bytree = 0.8,
    max_depth = 4,
    min_child_weight = 6,
    base_score = mean(model_xp_data$label)
  )

```


```{r}
full_train_xp <- xgboost::xgb.DMatrix(model.matrix(~ . + 0, data = model_xp_data %>% select(-label)),
                                       label = model_xp_data$label)
model_xp <- xgboost::xgboost(params = params, data = full_train_xp, nrounds = nrounds, verbose = 2)

vip(model_xp, num_features = 5)

```

```{r}
off_epa<- c(-0.7, 0.7, 0.1)
def_epa<- c(-0.7, 0.7, 0.1)
xp_make_rate_params<- c(0.8, 1.0, 0.03)
game_seconds_params <- c(420, 240, 120, 60, 30)
score_diff_params <- seq(-10, 10, 1)

two_pt_grid <- expand.grid(
  off_epa_in_5 = off_epa,
  def_epa_in_5 = def_epa,
  xp_make_rate = xp_make_rate_params,
  game_seconds_remaining = game_seconds_params,
  score_differential = score_diff_params
)

```


```{r}
two_success_preds <- data.frame(predict(success_2pt_rf, data.frame(two_pt_grid))$predictions) %>% rename(wp1 = predict.success_2pt_rf..data.frame.two_pt_grid...predictions)
two_fail_preds <- data.frame(predict(fail_2pt_rf, data.frame(two_pt_grid))$predictions) %>% rename(wp2 = predict.fail_2pt_rf..data.frame.two_pt_grid...predictions)
two_made_fg_preds <- data.frame(predict(made_xp_rf, data.frame(two_pt_grid))$predictions) %>% rename(wp3 = predict.made_xp_rf..data.frame.two_pt_grid...predictions)
two_miss_fg_preds <- data.frame(predict(miss_xp_rf, data.frame(two_pt_grid))$predictions) %>% rename(wp4 = predict.miss_xp_rf..data.frame.two_pt_grid...predictions)

```



```{r}
two_conver_preds <- data.frame(predict.glm(log_2pt, newdata = two_pt_grid, type = "response")) %>% rename(c1 = predict.glm.log_2pt..newdata...two_pt_grid..type....response..)
xp_preds <- data.frame(predict.glm(xp_logit, newdata = two_pt_grid, type = "response")) %>% rename(c2 = predict.glm.xp_logit..newdata...two_pt_grid..type....response..)



```


```{r}
two_point_preds <- cbind(two_pt_grid, two_success_preds, two_fail_preds, two_made_fg_preds, two_miss_fg_preds, two_conver_preds, xp_preds)

two_point_grid <- two_point_preds %>%
  ungroup() %>%
  mutate(k = wp3*c2 + wp4*(1-c2),
         a = wp1*c1 + wp2*(1-c1) - k)

```

```{r}
two_point_grid<- two_point_grid %>%
  mutate(off_epa_in_5 = round(off_epa_in_5, 2),
         def_epa_in_5 = round(def_epa_in_5))
```


```{r}
two_point_grid<- read_csv(url("https://raw.githubusercontent.com/tejseth/coach-consulting/master/two_point_grid.csv"))
```

```{r}
write.csv(two_point_grid, file = "2point_Grid.csv")
```











