---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


```{r}
library(tidyverse)
library(nflfastR)
library(nfl4th)
library(ranger)
library(vip)
library(shapper)
```


```{r}
pbp<- load_pbp(2015:2021)
```

```{r}
pbp_4th<- pbp %>%
  filter(down == 4)
```

#################################################################################

```{r}
pbp_went <- pbp_4th %>%
  filter(pass == 1 | rush == 1) %>%
  mutate(converted = ifelse(yards_gained >= ydstogo, 1, 0)) %>%
  filter(!is.na(converted)) %>%
  mutate(yardline_bucket = case_when(
    between(yardline_100, 91, 100) ~ "91 to 100 Yds to go",
    between(yardline_100, 81, 90) ~ "81 to 90 Yds to go",
    between(yardline_100, 71, 80) ~ "71 to 80 Yds to go",
    between(yardline_100, 61, 70) ~ "61 to 70 Yds to go",
    between(yardline_100, 51, 60) ~ "51 to 60 Yds to go",
    between(yardline_100, 41, 50) ~ "41 to 50 Yds to go",
    between(yardline_100, 31, 40) ~ "31 to 40 Yds to go",
    between(yardline_100, 21, 30) ~ "21 to 30 Yds to go",
    between(yardline_100, 11, 20) ~ "11 to 20 Yds to go",
    between(yardline_100, 1, 10) ~ "1 to 10 Yds to go",
  ))

```


```{r}
convert_rate<- pbp_went %>%
  group_by(yardline_bucket, ydstogo) %>%
  summarize(plays = n(),
            convert_rate = mean(converted)) %>%
  filter(plays >= 25, ydstogo <= 7) 

```

```{r}
convert_rate %>%
  mutate(`Yards to Go` = as.factor(ydstogo)) %>%
  ggplot(aes(x = yardline_bucket, y = convert_rate, group = `Yards to Go`)) +
  geom_smooth(aes(color = `Yards to Go`), se = FALSE, size = 1.5) +
  theme_minimal() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "Yardline Bucket",
       y = "Conversion Rate",
       title = "4th Down Conversion Rates by Yards to Go and Yardline Bucket") +
  theme(axis.text = element_text(size = 12, angle = -45),
        plot.title = element_text(size = 20, face = "bold"))

```
###################################3
conversion model

```{r}
init_logit<- glm(converted ~ (ydstogo + yardline_100 + ydstogo:yardline_100),
                              data = pbp_went, family = "binomial")


summary(init_logit)
```


```{r}
pred_outcome<- ifelse(init_logit$fitted.values > 0.5, "1", "0")

```



```{r}
pbp_went<- pbp_went %>%
  mutate(pred = init_logit$fitted.values)

```


```{r}
pbp_went_select<- pbp_went %>%
  select(down, ydstogo, yardline_100, pred, converted)

pbp_went_select %>%
  filter(between(ydstogo, -15, 15)) %>%
  ggplot(aes(x = ydstogo)) +
  geom_smooth(aes(y= pred), color = "orange") +
  geom_point(aes(y = converted), alpha = 0.4, color = "blue") +
  theme_minimal() + 
  labs(y = "Conversion Rate",
       x = "To Go Distance") +
  scale_x_continuous()

```


#############################################33

FG Prob

```{r}
field_goals<- pbp %>%
  filter(field_goal_attempt == 1)


```



```{r}
field_goals <- field_goals %>%
  mutate(fg_made = ifelse(field_goal_result == "made", 1, 0))

```

```{r}
fg_per_game<- field_goals %>%
  select(game_id, kicker_player_id, kicker_player_name, game_seconds_remaining, fg_made)

```


```{r}
fg_missed<- fg_per_game %>%
  filter(fg_made == 0) %>%
  select(game_id, kicker_player_id, kicker_player_name, time_missed = game_seconds_remaining) %>%
  group_by(kicker_player_id, kicker_player_name) %>%
  mutate(count = row_number()) %>%
  ungroup() %>%
  distinct() %>%
  filter(count == 1)


fg_per_game<- fg_per_game %>%
  left_join(fg_missed, by = c("game_id", "kicker_player_id", "kicker_player_name"))

```



```{r}
fg_per_game <- fg_per_game %>%
  mutate(prev_missed = ifelse(game_seconds_remaining < time_missed, 1, 0),
         prev_missed = ifelse(is.na(prev_missed), 0, prev_missed)) %>%
  select(game_id, kicker_player_id, game_seconds_remaining, prev_missed)

field_goals <- field_goals %>%
  left_join(fg_per_game, by = c("game_id", "kicker_player_id", "game_seconds_remaining"))

```




```{r}
fg_logit<- glm(fg_made ~ yardline_100, data = field_goals, family = "binomial")
summary(fg_logit)

```


```{r}
field_goals %>%
  mutate(pred_prob = fg_logit$fitted.values) %>%
  ggplot(aes(x = yardline_100)) +
  geom_line(aes(y = pred_prob), color = "darkorange", size = 2) +
  geom_point(aes(y = fg_made), alpha = 0.4, color = "darkblue") +
  theme_minimal()


```


###########################################################

if go and if succeed

```{r}
success_4th<- pbp %>%
  filter(down == 4) %>%
  filter(rush == 1 | pass == 1) %>%
  filter(yards_gained >= ydstogo) %>%
  filter(!is.na(wpa)) %>%
  mutate(wpa = ifelse(wpa <0, -wpa, wpa))

```

#Add Gameflow Here on Game and Drive

```{r}
success_4th_rf<- ranger(wpa ~ game_seconds_remaining + ydstogo + yardline_100 + score_differential, data = success_4th, num.trees = 100, importance = "impurity")

vip(success_4th_rf)


```


###############


#Add Gameflow Here on Game and Drive


```{r}
fail_4th<- pbp %>%
  filter(down == 4) %>%
  filter(rush == 1 | pass == 1) %>%
  filter(yards_gained < ydstogo) %>%
  filter(!is.na(wpa)) %>%
  mutate(wpa = ifelse(wpa > 0, -wpa, wpa))


```

#Add Gameflow Here on Game and Drive

```{r}
fail_4th_rf<- ranger(wpa ~ game_seconds_remaining + ydstogo + yardline_100 + score_differential, data = success_4th, num.trees = 100, importance = "impurity")

vip(fail_4th_rf)

```


```{r}
made_fg<- pbp %>%
  filter(field_goal_result == "made") %>%
  filter(!is.na(wpa)) %>%
  filter(wpa < 0.75, wpa > -0.2) %>%
  mutate(wpa = ifelse(wpa < 0, -wpa, wpa))
  

```


#ADD TO MODEL LATER

```{r}
made_fg_rf <- ranger(wpa ~ game_seconds_remaining + ydstogo + yardline_100 + score_differential, data = made_fg, num.trees = 100, importance = "impurity")

vip(made_fg_rf)

```

```{r}
miss_fg<- pbp %>%
  filter(field_goal_result != "made") %>%
  filter(!is.na(wpa)) %>%
  mutate(wpa = ifelse(wpa > 0, -wpa, wpa))
  

```


#ADD TO MODEL LATER

```{r}
miss_fg_rf <- ranger(wpa ~ game_seconds_remaining + ydstogo + yardline_100 + score_differential, data = made_fg, num.trees = 100, importance = "impurity")

vip(miss_fg_rf)

```



```{r}
punts<- pbp %>%
  filter(punt_attempt == 1) %>%
  filter(!is.na(wpa)) 
  

```



```{r}
punt_rf <- ranger(wpa ~ game_seconds_remaining + ydstogo + yardline_100 + score_differential, data = made_fg, num.trees = 100, importance = "impurity")

vip(punt_rf)
```


################################################################################################

#MAKE IT SO EVERYTHING CAN BE INPUTTED


```{r}
yards_to_goal_params<- seq(5, 65, 5)
distance_params<- seq(1, 6, 1)
game_seconds_params<- c(2600, 2700, 1800, 1350, 900, 720, 420, 240, 120, 60, 20)
score_diff_params<- seq(-14, 11, 1)

hyper_grid<- expand.grid(
  yardline_100 = yards_to_goal_params,
  ydstogo = distance_params,
  game_seconds_remaining = game_seconds_params,
  score_differential = score_diff_params
)

```

```{r}
success_preds<- data.frame(predict(success_4th_rf, data.frame(hyper_grid))$predictions) %>%
  rename(wp1 = predict.success_4th_rf..data.frame.hyper_grid...predictions)

```


```{r}
fail_preds<- data.frame(predict(fail_4th_rf, data.frame(hyper_grid))$predictions) %>%
  rename(wp2 = predict.fail_4th_rf..data.frame.hyper_grid...predictions)


```

```{r}
made_fg_preds<- data.frame(predict(made_fg_rf, data.frame(hyper_grid))$predictions) %>%
  rename(wp3 = predict.made_fg_rf..data.frame.hyper_grid...predictions)


```


```{r}
miss_fg_preds<- data.frame(predict(miss_fg_rf, data.frame(hyper_grid))$predictions) %>%
  rename(wp4 = predict.miss_fg_rf..data.frame.hyper_grid...predictions)


```


```{r}
punt_preds<- data.frame(predict(punt_rf, data.frame(hyper_grid))$predictions) %>%
  rename(wp5 = predict.punt_rf..data.frame.hyper_grid...predictions)
```

```{r}
conver_preds <- data.frame(predict.glm(init_logit, newdata = hyper_grid, type = "response")) %>% rename(c1 = predict.glm.init_logit..newdata...hyper_grid..type....response..)

```



```{r}
fg_preds <- data.frame(predict.glm(fg_logit, newdata = hyper_grid, type = "response")) %>% rename(c2 = predict.glm.fg_logit..newdata...hyper_grid..type....response..)

```


```{r}

hyper_grid_preds<- cbind(hyper_grid, success_preds, fail_preds, made_fg_preds, miss_fg_preds, punt_preds, conver_preds, fg_preds)
```


```{r}
hyper_grid_preds <- hyper_grid_preds %>%
  mutate(wp5 = ifelse(yardline_100 < 35, NA, wp5))
```


```{r}
final_grid<- hyper_grid_preds %>%
  ungroup() %>%
  mutate(k_sup = (wp3*c2 + wp4 *(1-c2)),
         k = ifelse(k_sup > wp5, k_sup, wp5),
         a = wp1*c1 +wp2*(1-c1) - k) 

```


```{r}
write.csv(final_grid, file = "4th Down Grid.csv")

```

################################3

```{r}
fourth <- nfl4th:: load_4th_pbp(2015:2021)

```


```{r}
fourth <- fourth %>%
  mutate(
    should_go = dplyr::case_when(
      go_boost > 1 ~ 1,
      go_boost < -1 ~ 0,
      TRUE ~ 2))

```

```{r}

go_when_should <- fourth %>%
  filter(should_go == 1, !is.na(posteam)) %>%
  group_by(posteam, season) %>%
  summarize(count = n(),
            went_perc = mean(go, na.rm = T)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))



```

```{r}
kicked_when_shouldnt <- fourth %>%
  filter(should_go == 1, !is.na(posteam), go == 0) %>%
  group_by(posteam, season) %>%
  summarize(count = n(),
            avg_wpa = mean(wpa)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))
```


```{r}
write.csv(go_when_should, file = "Going When Should Data.csv")
write.csv(kicked_when_shouldnt, file = "Kicking When Shouldnt Datakick .csv")

```

```{r}
go_when_should %>%
  ggplot(aes(x = reorder(posteam, -went_perc), y = went_perc)) +
  geom_bar(aes(fill = team_color, color = team_color2), stat = "identity", alpha = 0.9) +
  geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.04) +
  scale_color_identity(aesthetics = c("fill", "color")) +
  theme_minimal() +
  labs(x = "Team",
       y = "Went % When Should",
       title = paste0("Teams That Went for 4th Downs When They Should Have, 2015-2021")) +
  theme(panel.grid.major.x = element_line(size = 0.1),
        legend.position = "none")
ggsave('4th-2021.png', width = 14, height = 10, dpi = "retina")

```


```{r}
go_when_should %>%
  arrange(-went_perc) %>%
  ungroup() %>%
  mutate(rank = row_number(),
         went_perc = round(went_perc, 1)) %>%
  select(rank, team_wordmark, count, went_perc) %>%
  gt() %>%
  text_transform(
    locations = cells_body(vars(team_wordmark)),
    fn = function(x){
      web_image(
        url = x,
        height = px(25)
      )
    }
  ) %>%
  cols_label(rank = "Rank",
              team_wordmark = "Team",
              count = "# of Decisions",
              went_perc = "% Went for It") %>%
  data_color(
    columns = vars(went_perc),
    colors = scales::col_numeric(
      c("#f87274", "#ffeb84", "#63be7b"), 
      domain = NULL)
  ) %>%
  cols_align(align = "center")

```

```{r}

kicked_when_shouldnt <- fourth %>%
  filter(season >= 2015, should_go == 1, !is.na(posteam), go == 0) %>%
  group_by(posteam) %>%
  summarize(count = n(),
            sum_wpa = -sum(wpa)) %>%
  left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

```



```{r}
kicked_when_shouldnt %>%
  ggplot(aes(x = reorder(posteam, -sum_wpa), y = sum_wpa)) +
  geom_bar(aes(fill = team_color, color = team_color2), stat = "identity", alpha = 0.9) +
  geom_image(aes(image = team_logo_espn), asp = 16/9, size = 0.04) +
  scale_color_identity(aesthetics = c("fill", "color")) +
  theme_minimal() +
  labs(x = "Team",
       y = "Total WPA Lost By Kicking",
       title = paste0("WPA Lost By Kicking When Teams Should Not Have, 2015-2021")) +
  theme(panel.grid.major.x = element_line(size = 0.1),
        legend.position = "none")
ggsave('shouldnt.png', width = 14, height = 10, dpi = "retina")

```

```






